spring:
  profiles:
    active: ${springProfilesActive:test}  # default test 환경
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none # update
  datasource:
    url: jdbc:sqlite:mydb.db
    driver-class-name: org.sqlite.JDBC
    username: ENC(0quG6FVbayjtAMT/26YQxA==)
    password: ENC(cOh6l6GKbZQdo8p9EE98/A==)
  sql:
    init:
      mode: always
  data:
    redis:
      host: 192.168.0.8
      port: 6379

jwt:
  access-token-expiration: 1800000      # 30분(밀리초 단위)
  refresh-token-expiration: 604800000   # 7일(밀리초 단위)

jasypt:
  encryptor:
    bean: jasyptEncryptor

server:
  shutdown: graceful