spring:
  profiles:
    active: ${springProfilesActive:test}  # default test 환경
    include: oauth
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none # update
  datasource:
    url: jdbc:sqlite:mydb.db
    driver-class-name: org.sqlite.JDBC
    username: ENC(0quG6FVbayjtAMT/26YQxA==)
    password: ENC(cOh6l6GKbZQdo8p9EE98/A==)
  sql:
    init:
      mode: always
  data:
    redis:
      host: 192.168.0.8
      port: 6379
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ENC(l8HvF1/xCISpDoQWTjyM+yhI9+03S1+syRDScg5CAaM=)
            client-secret: ENC(D7rqCq/bMR2q61t+k0UizpHik4Mnoa9s)
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: name, email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  access-token-expiration: 1800000      # 30분(밀리초 단위)
  refresh-token-expiration: 604800000   # 7일(밀리초 단위)

jasypt:
  encryptor:
    bean: jasyptEncryptor

server:
  shutdown: graceful