DROP TABLE IF EXISTS USER;

CREATE TABLE IF NOT EXISTS USER (
    ID TEXT PRIMARY KEY,
    PASSWORD TEXT NOT NULL,
    NAME TEXT NOT NULL,
    AUTH TEXT NOT NULL,
    TOKEN TEXT NOT NULL
);

DROP TABLE IF EXISTS TODO;

CREATE TABLE IF NOT EXISTS TODO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CONTENT TEXT
);